"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 10

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - fl1
          - fl2
          - fl3
          - fr1
          - fr2
          - fr3
          - bl1
          - bl2
          - bl3
          - br1
          - br2
          - br3

      gains:
        fl1 : {p: 150, d: 5, i: 0.5}
        fl2 : {p: 150, d: 5, i: 0.5}
        fl3 : {p: 150, d: 5, i: 0.5}
        fr1 : {p: 150, d: 5, i: 0.5}
        fr2 : {p: 150, d: 5, i: 0.5}
        fr3 : {p: 150, d: 5, i: 0.5}
        bl1 : {p: 150, d: 5, i: 0.5}
        bl2 : {p: 150, d: 5, i: 0.5}
        bl3 : {p: 150, d: 5, i: 0.5}
        br1 : {p: 150, d: 5, i: 0.5}
        br2 : {p: 150, d: 5, i: 0.5}
        br3 : {p: 150, d: 5, i: 0.5}
